#!/usr/bin/env python3
"""
make_tables.py — Regenerate Tables 2–3 and a ledger-view audit table from production-run JSONs (the paper’s Table 4 is regenerated by delta_sensitivity.py).
==========================================================================
Reads the JSON written by pinn_production_float64_full.py and reproduces,
without any retraining:

  Table 2  : Per-alloy parameter estimates (primary basin), with both
             mean±std and robust (median / MAD) statistics.
  Table 3  : Cross-alloy comparison (sign counts, audit counts).
  Table 4  : Mass-balance / audit summary (model-free Δ, violation totals).
  Tables S : Per-seed listings (one per alloy), classification included.

Classification logic is identical to the production script:
  Stage 1: converged (L-BFGS steps >= 50, stored in JSON as `converged`)
  Stage 2: greedy parameter-space clustering in (log10 D0, alpha)

Usage:
  python make_tables.py [path/to/production_results_float64_full.json]
Outputs Markdown to stdout and writes tables_generated.md next to the JSON.

Dependencies: numpy only (plus stdlib).
"""
import json
import sys
import os
import numpy as np

# Alloy densities (g/cm^3) — not stored in the JSON, kept here explicitly.
RHO = {"316SS": 8.0, "Hastelloy-N": 8.86, "316H": 8.0}

# Expected diagnostic sign per alloy (for sign-count tables).
EXPECTED_SIGN = {"316SS": "negative", "Hastelloy-N": "negative", "316H": "positive"}


def classify_basins(conv, tol_logD0=0.3, tol_alpha=0.3):
    """Greedy clustering in (log10 D0, alpha); loss used only for ordering."""
    basins = []
    for r in sorted(conv, key=lambda r: r["loss"]):
        placed = False
        for b in basins:
            c = b[0]
            if (abs(np.log10(r["D0"]) - np.log10(c["D0"])) < tol_logD0
                    and abs(r["alpha"] - c["alpha"]) < tol_alpha):
                b.append(r)
                placed = True
                break
        if not placed:
            basins.append([r])
    primary = basins[0] if basins else []
    secondary = [r for b in basins[1:] for r in b]
    return primary, secondary


def med_mad(vals):
    """Median and scaled MAD (robust sigma equivalent)."""
    v = np.asarray(vals, dtype=float)
    med = float(np.median(v))
    mad = float(1.4826 * np.median(np.abs(v - med)))
    return med, mad


def fmt_e(x):
    return f"{x:.2e}"


def conversion_factor(alloy, meta):
    c_range = meta["C_bulk"] - meta["C_surface"]
    L_depth = meta["domain_um"] * 1e-4  # cm
    return RHO[alloy] * (c_range / 100.0) * L_depth * 1000.0  # mg/cm^2 per unit w


def main(path):
    paths = path if isinstance(path, list) else [path]
    data = {}
    for p in paths:
        with open(p, encoding="utf-8") as f:
            data.update(json.load(f))
    path = paths[0]

    lines = []
    P = lines.append
    P(f"# Tables regenerated from `{os.path.basename(path)}`")
    first = next(iter(data.values()))
    P(f"\nProtocol: {first.get('protocol', 'n/a')}  ")
    P(f"Precision: {first.get('float_precision', 'n/a')}, run tag: "
      f"{first.get('run_tag', 'n/a')}, seeds: {first.get('seeds_run', 'n/a')}\n")

    classified = {}
    for alloy, block in data.items():
        seeds = block["seeds"]
        conv = [r for r in seeds if r["converged"]]
        stalled = [r for r in seeds if not r["converged"]]
        primary, secondary = classify_basins(conv)
        classified[alloy] = dict(primary=primary, secondary=secondary,
                                 stalled=stalled, meta=block, n=len(seeds))

    # ------------------------------------------------------------------
    # Table 2 — Parameter estimates (primary basin)
    # ------------------------------------------------------------------
    P("## Table 2. Inverse-estimated parameters (primary family)\n")
    P("| Alloy | n(prim) | D0 mean±SD (cm²/s) | D0 median [MAD] | "
      "α mean±SD | α median [MAD] | D_wall mean±SD (cm²/s) | D_wall median [MAD] | "
      "⟨D⟩ = D0(1+α/2) median [MAD] | EDS NRMSE (%) |")
    P("|---|---|---|---|---|---|---|---|---|---|")
    for alloy, c in classified.items():
        pri = c["primary"]
        if not pri:
            P(f"| {alloy} | 0 | – | – | – | – | – | – | – | – |")
            continue
        D0 = [r["D0"] for r in pri]
        al = [r["alpha"] for r in pri]
        dw = [r["D_wall"] for r in pri]
        nr = [r["eds_nrmse"] for r in pri]
        # range-averaged diffusivity, analytic for the linear closure:
        # <D> = (1/1) * \int_0^1 D0(1+a(1-Cn)) dCn = D0 (1 + a/2)
        davg = [r["D0"] * (1.0 + r["alpha"] / 2.0) for r in pri]
        d0m, d0d = med_mad(D0)
        alm, ald = med_mad(al)
        dwm, dwd = med_mad(dw)
        dam, dad = med_mad(davg)
        P(f"| {alloy} | {len(pri)} "
          f"| {fmt_e(np.mean(D0))} ± {fmt_e(np.std(D0))} "
          f"| {fmt_e(d0m)} [{fmt_e(d0d)}] "
          f"| {np.mean(al):+.3f} ± {np.std(al):.3f} "
          f"| {alm:+.3f} [{ald:.3f}] "
          f"| {fmt_e(np.mean(dw))} ± {fmt_e(np.std(dw))} "
          f"| {fmt_e(dwm)} [{fmt_e(dwd)}] "
          f"| {fmt_e(dam)} [{fmt_e(dad)}] "
          f"| {np.mean(nr):.1f} ± {np.std(nr):.1f} |")

    # Robust-outlier note (>3×MAD from median in D_wall)
    P("\n**D_wall outliers (>3×MAD from median within primary family):**\n")
    any_out = False
    for alloy, c in classified.items():
        pri = c["primary"]
        if len(pri) < 3:
            continue
        dw = np.array([r["D_wall"] for r in pri])
        med, mad = med_mad(dw)
        if mad == 0:
            continue
        for r in pri:
            if abs(r["D_wall"] - med) > 3 * mad:
                any_out = True
                P(f"- {alloy} seed {r['seed']}: D_wall = {fmt_e(r['D_wall'])} "
                  f"(median {fmt_e(med)}), loss = {r['loss']:.5f} "
                  f"(family best {min(x['loss'] for x in pri):.5f}) — "
                  f"equal-loss alternative; see identifiability discussion.")
    if not any_out:
        P("- none")

    # ------------------------------------------------------------------
    # Table 3 — Cross-alloy comparison
    # ------------------------------------------------------------------
    P("\n## Table 3. Cross-alloy comparison\n")
    P("| Alloy | T | Converged | Primary / Sec / Stalled | Sign consistency "
      "| Audit pass (all seeds) | Retries used |")
    P("|---|---|---|---|---|---|---|")
    for alloy, c in classified.items():
        meta = c["meta"]
        pri, sec, stl = c["primary"], c["secondary"], c["stalled"]
        seeds = meta["seeds"]
        n = c["n"]
        exp = EXPECTED_SIGN[alloy]
        if exp == "negative":
            n_sign_all = sum(1 for r in seeds if r["alpha"] < 0)
            sign_str = f"{n_sign_all}/{n} α<0"
        else:
            n_sign_all = sum(1 for r in seeds if r["alpha"] > 0)
            sign_str = f"{n_sign_all}/{n} α>0"
        n_audit = sum(1 for r in seeds if r["audit"]["audit_pass"])
        n_retry = sum(r["retries"] for r in seeds)
        P(f"| {alloy} | {meta['temperature']} | {len(pri) + len(sec)}/{n} "
          f"| {len(pri)} / {len(sec)} / {len(stl)} | {sign_str} "
          f"| {n_audit}/{n} | {n_retry} |")

    # ------------------------------------------------------------------
    # Table 4 — Mass balance / audit (model-free Δ and violation totals)
    # ------------------------------------------------------------------
    P("\n## Table 4 (ledger view). Mass-balance audit (all seeds; signed violation w(0,1) + w_gap)\n")
    P("Δ_norm = w_target − ∫(1−u)dx (dense grid, t=1); "
      "Δ_mg = Δ_norm × conversion; violation = w(0,1) + w_gap.\n")
    P("| Alloy | w_target | ∫(1−u) mean±SD | Δ_norm | Δ (mg/cm²) "
      "| unexplained fraction | violation mean±SD | audit |")
    P("|---|---|---|---|---|---|---|---|")
    for alloy, c in classified.items():
        meta = c["meta"]
        seeds = meta["seeds"]
        conv_f = conversion_factor(alloy, meta)
        wt = seeds[0]["audit"]["w_target"]
        integ = np.array([r["audit"]["integral_1_minus_u"] for r in seeds])
        viol = np.array([r["audit"]["w_pred_at_x0_t1"] + r["audit"]["w_gap"]
                         for r in seeds])
        d_norm = wt - integ.mean()
        d_mg = d_norm * conv_f
        frac = d_norm / wt if wt != 0 else float("nan")
        n_audit = sum(1 for r in seeds if r["audit"]["audit_pass"])
        P(f"| {alloy} | {wt:.4f} | {integ.mean():.4f} ± {integ.std():.4f} "
          f"| {d_norm:+.4f} | {d_mg:+.3f} | {frac:+.1%} "
          f"| {viol.mean():+.4f} ± {viol.std():.4f} | {n_audit}/{len(seeds)} |")
    P("\nNote: for audit-FAIL alloys, `mass_ratio` and total loss are "
      "bookkeeping artefacts and must not be quoted; Δ and the violation "
      "total are the physically meaningful quantities. The unexplained fraction above is quoted against the ledger w_target (the last-fed anchor); the paper’s declared deficit uses the replicate-mean reference where replicates exist (Section 4.4) and the convention grid of tools/delta_sensitivity.py — for 316H this reads ≈95 %, not the ≈92.5 % shown here. The signed violation of this table is the reporting convention of Section 4.3 (algebraically w(1,1) − ∫(1−u)dx, the unmet remainder); the paper’s Table 4 (model-free deficits under the convention grid) is regenerated by tools/delta_sensitivity.py from the digitized data alone.")

    # ------------------------------------------------------------------
    # Tables S — per-seed listings
    # ------------------------------------------------------------------
    for alloy, c in classified.items():
        meta = c["meta"]
        P(f"\n## Table S — {alloy} ({meta['temperature']}, "
          f"{meta['duration']}), per-seed results\n")
        P("| Seed | α | D0 (cm²/s) | D_wall (cm²/s) | Loss | EDS RMSE (wt%) "
          "| w(1,1) | ∫(1−u) | w(0,1) | w_gap | Audit | L-BFGS | Retry | Status |")
        P("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|")
        status_of = {}
        for r in c["primary"]:
            status_of[r["seed"]] = "PRIMARY"
        for r in c["secondary"]:
            status_of[r["seed"]] = "secondary"
        for r in c["stalled"]:
            status_of[r["seed"]] = "STALLED"
        ordered = (c["primary"] + c["secondary"]
                   + sorted(c["stalled"], key=lambda r: r["loss"]))
        for r in ordered:
            a = r["audit"]
            P(f"| {r['seed']} | {r['alpha']:+.3f} | {fmt_e(r['D0'])} "
              f"| {fmt_e(r['D_wall'])} | {r['loss']:.5f} | {r['eds_rmse']:.2f} "
              f"| {a['w_pred_at_x1_t1']:+.4f} | {a['integral_1_minus_u']:+.4f} "
              f"| {a['w_pred_at_x0_t1']:+.4f} | {a['w_gap']:+.4f} "
              f"| {'ok' if a['audit_pass'] else 'FAIL'} "
              f"| {r['lbfgs_steps']} | {r['retries']} | {status_of[r['seed']]} |")

    out = "\n".join(lines)
    print(out)
    out_path = os.path.join(os.path.dirname(os.path.abspath(path)),
                            "tables_generated.md")
    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(out + "\n")
        print(f"\n[written to {out_path}]", file=sys.stderr)
    except OSError as e:
        print(f"\n[could not write file: {e}]", file=sys.stderr)


if __name__ == "__main__":
    # Ignore kernel options (e.g. "-f kernel.json") when run inside Jupyter.
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if args:
        p = args if len(args) > 1 else args[0]
    else:
        # Default roster: the coupled production ledgers of the current
        # generation (Tables 3-4 and the coupled rows). For the reported
        # EDS-only ensembles run e.g.:
        #   python tools/make_tables.py results/HN_eds_only.json results/316H_eds_only.json
        from pathlib import Path
        base = Path(__file__).resolve().parent.parent / "results"
        p = [str(base / f) for f in
             ("316SS_coupled.json", "HN_coupled.json", "316H_coupled.json")]
    main(p)
