"""
All manuscript figures, generated from the campaign ledgers and the released
solvers. This script is part of the repository: every figure regenerates from
the same single-source code that produced the ledger.

  Fig. 1  316SS: digitized concentration profile and the coupled-inversion
          prediction of the median-alpha production seed.
  Fig. 2  316SS: predicted cumulative mass loss w(1,t)-conv versus the six
          gravimetric anchors.
  Fig. 3  Hastelloy-N and 316H: digitized profiles and the EDS-only
          predictions of the median-alpha production seeds.
  Fig. 4  The (alpha, Delta) diagnostic plane with the three alloys located.
  Fig. 5  Violation conservation across the coupled seeds of the two
          deficit alloys.

Figures 4-5 read the ledgers only (seconds). Figures 1-3 RETRAIN the median
seed with the released solver (deterministic; ~20 min per panel), then VERIFY
that the retrained (D0, alpha) equal the archived ledger entry bit-for-bit
before a single curve is drawn - the figure generation is itself a
reproducibility witness. A mismatch aborts with an error.

Usage (from re_run/):
    python tools/make_figs_all.py                 # everything
    python tools/make_figs_all.py --figs 4,5      # ledger-only figures
    python tools/make_figs_all.py --figs 1,2      # 316SS panels only
Optional: --results DIR (default results), --out DIR (default figs)
"""
import json, sys, statistics as st
from pathlib import Path

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "src"))
sys.path.insert(0, str(HERE))

# ----------------------------------------------------------------- options
args = sys.argv[1:]
def opt(name, default):
    if name in args:
        return args[args.index(name) + 1]
    return default
FIGS = set(opt("--figs", "1,2,3,4,5").split(","))
RESULTS = Path(opt("--results", "results"))
OUT = Path(opt("--out", "figs"))
OUT.mkdir(exist_ok=True)

# ------------------------------------------------------- ledger utilities
def load(fname, alloy):
    return json.load(open(RESULTS / fname, encoding="utf-8"))[alloy]["seeds"]

def median_row(fname, alloy):
    rows = load(fname, alloy)
    med = st.median(r["alpha"] for r in rows)
    return next(r for r in rows if r["alpha"] == med)

def reported_alpha(fname, alloy):
    """Median [MAD] of alpha over the primary solution family (the Table 2
    statistics: median and SCALED MAD), computed with the same classify_basins implementation the
    tables use - single source, no fork."""
    import importlib.util
    _spec = importlib.util.spec_from_file_location(
        "make_tables", HERE / "make_tables.py")
    _mt = importlib.util.module_from_spec(_spec)
    _spec.loader.exec_module(_mt)
    rows = [r for r in load(fname, alloy) if r.get("converged", True)]
    pri, _sec = _mt.classify_basins(rows, tol_logD0=0.30, tol_alpha=0.30)
    a = [r["alpha"] for r in pri]
    med = st.median(a)
    return med, 1.4826 * st.median([abs(x - med) for x in a])

def retrain_verified(run_pinn, cfg, row):
    """Retrain one seed with the released solver and verify bit-identity of
    (D0, alpha) against the archived ledger entry before returning the model."""
    print(f"  retraining {cfg['name']} seed {row['seed']} "
          f"(deterministic, ~20 min) ...", flush=True)
    r = run_pinn(cfg, row["seed"], return_model=True)
    for k in ("D0", "alpha"):
        if r[k] != row[k]:
            raise RuntimeError(
                f"bit-identity FAILED for {cfg['name']} seed {row['seed']}: "
                f"{k} retrained {r[k]!r} != ledger {row[k]!r}")
    print(f"    bit-identity verified: D0 and alpha match the ledger exactly.")
    return r["model"]

def profile_curve(model, cfg, n=400):
    x = np.linspace(0.0, 1.0, n)
    X = np.column_stack([x, np.ones(n)])
    u = model.predict(X)[:, 0]
    C_range = cfg["C_bulk"] - cfg["C_surface"]
    return x * cfg["domain_um"], cfg["C_surface"] + u * C_range

def mass_curve(model, cfg, n=200):
    t = np.linspace(0.0, 1.0, n)
    X = np.column_stack([np.ones(n), t])
    w = model.predict(X)[:, 1]
    C_range = cfg["C_bulk"] - cfg["C_surface"]
    conv = cfg["rho"] * (C_range / 100.0) * (cfg["domain_um"] * 1e-4) * 1000.0
    return t * cfg["T_max_hr"], w * conv

# ------------------------------------------------- certified deficit values
# Percent of the gravimetric record, audit-convention anchor. Source: Table 4
# and Table S9 (generated by tools/delta_sensitivity.py). Constants on
# purpose: the Delta conventions have a single implementation, which this
# figure must not fork.
DELTA = {
    # centrals: production/depletion-window headline readings; bands: the full
    # twelve-cell convention-and-window grid of Table S19 (2 baselines x
    # 2 integrands x 3 windows), regenerated 2026-08 from the single-source
    # make_stables generator.
    "316SS":       {"band": (-102.3, 18.2), "central": -45.2, "show": "-45 %"},
    "Hastelloy-N": {"band": (59.5, 88.7),   "central": 84.0,  "show": "+84 %"},
    "316H":        {"band": (90.5, 94.7),   "central": 94.5,  "show": "+95 %"},
}

# ------------------------------------------------------------------ figures
def fig1(model, cfg):
    fig, ax = plt.subplots(figsize=(6.2, 4.4))
    # +-1 sigma plateau-scatter band (sigma ~ 1.25 wt%, Section 4.1): the noise
    # level that sets the identifiability limits of Section S6.
    ax.axhspan(cfg["C_bulk"] - 1.25, cfg["C_bulk"] + 1.25, color="0.92",
               zorder=0, label="±1σ plateau scatter")
    ax.plot(cfg["depth_um"], cfg["Cr_wt"], "o", ms=5, color="0.25",
            label="digitized EDS data (Zheng et al.)")
    xd, Cr = profile_curve(model, cfg)
    ax.plot(xd, Cr, "-", lw=2, color="tab:blue",
            label="coupled inversion, median-\u03b1 seed (3000 h)")
    ax.set_xlabel("depth (\u03bcm)"); ax.set_ylabel("Cr (wt%)")
    ax.legend(fontsize=9); fig.tight_layout()
    fig.savefig(OUT / "fig1_316ss_profile.png", dpi=300); print("fig1 written")

def fig2(model, cfg):
    import json as _json
    fig, (ax, ax2) = plt.subplots(2, 1, figsize=(6.9, 6.1))
    # ---- (a) mass channel with the audit-tolerance ribbon ----
    t_hr, m = mass_curve(model, cfg)
    C_range = cfg["C_bulk"] - cfg["C_surface"]
    conv = cfg["rho"] * (C_range / 100.0) * (cfg["domain_um"] * 1e-4) * 1000.0
    ax.plot(t_hr, m, "-", lw=1.1, color="tab:blue", alpha=0.5,
            label="w(1,t)\u00b7conv (inter-anchor: unconstrained; audited in (b))")
    t_anchor = np.asarray(cfg["mass_times_hr"], float)
    Xa = np.column_stack([np.ones(len(t_anchor)), t_anchor / cfg["T_max_hr"]])
    wa = model.predict(Xa)[:, 1] * conv
    ax.plot(t_anchor, wa, "x", ms=9, mew=2.2, color="tab:blue", label="model at anchor times")
    ax.plot(cfg["mass_times_hr"], cfg["dW_data"], "s", ms=7, color="0.25", mfc="none",
            label="gravimetric anchors")
    ax.set_xlabel("time (h)"); ax.set_ylabel("mass loss (mg/cm\u00b2)")
    ax.legend(fontsize=8, loc="lower right")
    ax.text(0.02, 0.95, "(a)", transform=ax.transAxes, fontsize=11, fontweight="bold", va="top")
    # ---- (b) audited channels over the time sweep, all production seeds ----
    led = None
    for p in ("results/316SS_coupled.json", "../results/316SS_coupled.json"):
        try:
            led = _json.load(open(p, encoding="utf-8")); break
        except FileNotFoundError:
            continue
    if led is None:
        raise FileNotFoundError("316SS_coupled.json not found for fig2 panel (b)")
    blk = next(v for v in led.values() if isinstance(v, dict) and "seeds" in v)
    mx0 = mxg = 0.0
    for k, r in enumerate(blk["seeds"]):
        ts = r["audit"].get("time_sweep")
        if not ts:
            continue
        t = np.asarray(ts["t_grid"], float)
        w0 = np.asarray(ts["w0_of_t"], float)
        wg = np.asarray(ts["w_gap_of_t"], float)
        mx0 = max(mx0, np.abs(w0).max()); mxg = max(mxg, np.abs(wg).max())
        ax2.plot(t, w0, "-", lw=0.9, color="tab:blue", alpha=0.45,
                 label="w(0,t) per seed" if k == 0 else None)
        ax2.plot(t, wg, "-", lw=0.9, color="tab:orange", alpha=0.45,
                 label="w~gap~(t) per seed".replace("~", "") if k == 0 else None)
    ax2.axhspan(-0.05, 0.05, color="0.88", alpha=0.6, zorder=0, label="audit tolerance \u00b10.05")
    ax2.axvline(1.0, color="0.35", lw=1.0, ls=":")
    ax2.text(1.0, ax2.get_ylim()[1] * 0.9 if ax2.get_ylim()[1] else 0.05, " t\u2081", fontsize=9, color="0.35")
    ax2.text(0.02, 0.06, f"max |w(0,t)| = {mx0:.3f}   max |w_gap(t)| = {mxg:.3f}",
             transform=ax2.transAxes, fontsize=8.5)
    ax2.set_xlabel("normalized time t"); ax2.set_ylabel("audited channels (normalized)")
    ax2.set_ylim(-0.075, 0.075)
    ax2.legend(fontsize=8, loc="upper right")
    ax2.text(0.02, 0.95, "(b)", transform=ax2.transAxes, fontsize=11, fontweight="bold", va="top")
    fig.tight_layout()
    fig.savefig(OUT / "fig2_316ss_mass.png", dpi=300); print("fig2 written (two-panel)")

def fig3(models_cfgs):
    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.6))
    import matplotlib.transforms as mtransforms
    for ax, (model, cfg, src) in zip(axes, models_cfgs):
        ax.plot(cfg["depth_um"], cfg["Cr_wt"], "o", ms=5, color="0.25",
                label="digitized EDS data (Sankar et al.)")
        xd, Cr = profile_curve(model, cfg)
        ax.plot(xd, Cr, "-", lw=2, color="tab:red",
                label="EDS-only inversion, median-\u03b1 seed")
        ax.axvline(cfg["domain_um"], color="0.45", lw=1.0, ls=":")
        trans = mtransforms.blended_transform_factory(ax.transData, ax.transAxes)
        ax.text(cfg["domain_um"], 1.02, "analysis domain", transform=trans,
                ha="center", va="bottom", fontsize=7.5, color="0.35")
        ax.set_title(cfg["name"]); ax.set_xlabel("depth (\u03bcm)")
    axes[0].set_ylabel("Cr (wt%)")
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=2, fontsize=9,
               frameon=False)
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    fig.savefig(OUT / "fig3_sankar_profiles.png", dpi=300); print("fig3 written")

def fig4():
    pts = [
        ("316SS",       "316SS_coupled.json",  "316SS",       "tab:blue"),
        ("Hastelloy-N", "HN_eds_only.json",    "Hastelloy-N", "tab:orange"),
        ("316H",        "316H_eds_only.json",  "316H",        "tab:red"),
    ]
    fig, ax = plt.subplots(figsize=(6.4, 5.0))
    for name, fn, key, color in pts:
        a, mad = reported_alpha(fn, key)
        dd = DELTA[name]; lo, hi = dd["band"]
        if dd["central"] is None:
            ax.errorbar(a, 0.5 * (lo + hi), xerr=mad,
                        yerr=[[0.5 * (hi - lo)], [0.5 * (hi - lo)]],
                        fmt="s", ms=8, color=color, capsize=4, lw=1.5, zorder=3)
            ax.annotate(f"{name}\n(\u03b1 = {a:+.2f}, \u0394 within systematics)",
                        (a, hi), textcoords="offset points", xytext=(10, 4),
                        fontsize=9.5, color=color)
        else:
            c = dd["central"]
            ax.errorbar(a, c, xerr=mad, yerr=[[c - lo], [hi - c]],
                        fmt="o", ms=9, color=color, capsize=4, lw=1.5, zorder=3)
            dx, dy, ha = (14, -46, "left") if name == "Hastelloy-N" else (0, -54, "center")
            ax.annotate(f"{name}\n(\u03b1 = {a:+.2f}, \u0394 = {dd['show']})",
                        (a, c), textcoords="offset points", xytext=(dx, dy),
                        fontsize=9.5, color=color, ha=ha)
    ax.axvline(0, color="0.4", lw=0.8, ls="--")
    ax.axhline(0, color="0.4", lw=0.8, ls="--")
    ax.set_xlabel(r"shape index  $\alpha = D_\mathrm{wall}/D_0 - 1$  (sign: transport regime)")
    ax.set_ylabel(r"mass deficit  $\Delta$  (% of gravimetric loss)")
    ax.set_xlim(-1.05, 1.05); ax.set_ylim(-118, 112)
    ax.text(-1.0, -112, "lattice-dominated (\u03b1 < 0)", fontsize=9,
            color="0.35", va="bottom")
    ax.text(1.0, -112, "short-circuit-dominated (\u03b1 > 0)", fontsize=9,
            color="0.35", va="bottom", ha="right")
    fig.tight_layout()
    fig.savefig(OUT / "fig4_diagnostic_plane.png", dpi=300); print("fig4 written")

def fig5():
    panels = [("Hastelloy-N", "HN_coupled.json"), ("316H", "316H_coupled.json")]
    fig, axes = plt.subplots(1, 2, figsize=(9.6, 4.2))
    for ax, (alloy, fn) in zip(axes, panels):
        rows = sorted(load(fn, alloy), key=lambda r: r["seed"])
        gap = [abs(r["audit"]["w_gap"]) for r in rows]
        w0 = [abs(r["audit"]["w_pred_at_x0_t1"]) for r in rows]
        x = np.arange(len(rows))
        ax.bar(x, gap, color="tab:blue", label=r"$|w_\mathrm{gap}|$ (between-collocation)")
        ax.bar(x, w0, bottom=gap, color="tab:orange", label=r"$|w(0,1)|$ (boundary lift)")
        tot = [r["audit"]["w_pred_at_x0_t1"] + r["audit"]["w_gap"] for r in rows]
        ax.axhline(st.mean(tot), color="k", lw=1.0, ls="--")
        ax.set_title(f"{alloy}: signed violation total {st.mean(tot):.4f} \u00b1 {st.stdev(tot):.4f}")
        ax.set_xticks(x); ax.set_xticklabels([str(r["seed"]) for r in rows], fontsize=8)
        ax.set_xlabel("seed")
    axes[0].set_ylabel("audited conservation violation (normalized mass units)")
    axes[0].legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(OUT / "fig5_violation_conservation.png", dpi=300); print("fig5 written")

# --------------------------------------------------------------------- main
if __name__ == "__main__":
    if FIGS & {"1", "2", "3"}:
        # runtime configurations come from the SOLVER modules, which merge the
        # alloy data with the protocol knobs (w_mass) - never from alloy_configs
        # directly, which by design carries data only.
        import pinn_production_coupled as PC
        import pinn_eds_only as PE
        coupled_run, eds_run = PC.run_pinn, PE.run_pinn
    if FIGS & {"1", "2"}:
        row = median_row("316SS_coupled.json", "316SS")
        model = retrain_verified(coupled_run, PC.CFG_316SS, row)
        if "1" in FIGS: fig1(model, PC.CFG_316SS)
        if "2" in FIGS: fig2(model, PC.CFG_316SS)
    if "3" in FIGS:
        mc = []
        for cfg, fn, key in [(PE.ALLOY_HASTN, "HN_eds_only.json", "Hastelloy-N"),
                             (PE.ALLOY_316H, "316H_eds_only.json", "316H")]:
            row = median_row(fn, key)
            mc.append((retrain_verified(eds_run, cfg, row), cfg,
                       "Sankar et al."))
        fig3(mc)
    if "4" in FIGS: fig4()
    if "5" in FIGS: fig5()